---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: detector
spec:
  selector:
    matchLabels:
      app: detector
  replicas: 1
  template:
    metadata:
      labels:
        app: detector
    spec:
      containers:
      - name: detector-server
        image: subfuzion/netcat:latest
        command: ["nc", "-l", "-k", "80"]
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: detector-service
spec:
  # type: NodePort
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: detector